apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: 2tier-backend
  namespace: 2tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
        labels:
          app: backend
    spec:
      serviceAccountName: app-sa
      containers:
          - name: backend-container 
            image: aniketu/2tier-backend:v2
            imagePullPolicy: Always
            env:
              - name: PGHOST  
                valueFrom:
                  configMapKeyRef:
                    name: config
                    key: PGHOST
              - name: PGPORT
                valueFrom:
                  configMapKeyRef:
                    name: config
                    key: PGPORT
              - name: PGDATABASE
                valueFrom:
                  configMapKeyRef:
                    name: config
                    key: PGDATABASE
              - name: PGUSER
                valueFrom:
                  configMapKeyRef:
                    name: config
                    key: PGUSER
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: PGPASSWORD
            readinessProbe:
              httpGet:
                path: /api/health
                port: 3001
              initialDelaySeconds: 15
              periodSeconds: 10
            
            ports:
              - containerPort: 3001
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
---
apiVersion: v1 
kind: Service 
metadata:
  name: backend-service
  namespace: 2tier
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
    
