name: frontend build and push docker image to dockerhub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: change directory to frontend
        run: cd /frontend 
      - name: build image
        run: docker build -t image .
      - name: list the image
        run: docker images
        
