name: check docker apiVersion
on:
  push:
    branches:
      - main
jobs:
  check docker version:
    runs-on: ubuntu-latest
    steps:
      - name: check docker apiVersion
        run: docker --version